def build(bld):
  bld(features     = 'cxx cprogram',
      source       = 'performance_test.cpp',
      target       = 'wat_performance_test',
      includes     = '.',
      uselib_local = 'wat_array')
