def build(bld):
  bld(features     ='cxx cshlib',
      source       = 'wat_array.cpp bit_array.cpp',
      name         = 'wat_array',
      target       = 'wat_array',
      includes     = '.')
  bld(features     ='cxx cstaticlib',
      source       = 'wat_array.cpp bit_array.cpp',
      name         = 'wat_array',
      target       = 'wat_array',
      includes     = '.')
  
  bld.install_files('${PREFIX}/include/wat_array', bld.path.ant_glob('*.hpp'))
